pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build-Test') {
            agent {
                docker {
                    image 'node:lts-buster-slim'
                    args '-p 3000:3000'
                    reuseNode true
                }
            }
            steps {
                sh 'npm install'

                sh 'chmod +x ./jenkins/scripts/test.sh'
                sh './jenkins/scripts/test.sh'

                sh 'chmod +x ./jenkins/scripts/deliver.sh'
                sh 'chmod +x ./jenkins/scripts/kill.sh'
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Build-Deploy') {
            steps {
                sh 'whoami'
                sh 'pwd'
                sh 'ls -la'
                sh 'docker ps -a'
                sh 'docker images'
                sh 'docker build -t testreact ./build'
                sh 'docker images'
            }
        }
    }
}